### ISSUE TITLE
Add property's name to SymbolProperty

### ISSUE THREAD

**Issue by chipnesh** [wowselim/goldfinch#5]
Hello.
I was looking for some plugin to iterate over an object's properties and found this project.
It is pretty cool and does everything I need, but one thing is missing.
It would really be helpful if it is possible to access the property's name. Maybe you can place it right inside of SymbolProperty class.

**Comment by wowselim** [comment]
Hi, do you have a use case for this feature? And what do you mean by SymbolProperty?
